### ISSUE TITLE
Does it support incremental training?

### ISSUE THREAD

**Issue by KangTomwk** [ertis-research/kafka-ml#21]
hi, do you involve kafka-ml incremental training?

**Comment by cmfer** [comment]
Hi there,
Incremental training is not available in Kafka-ML. If you wanna collaborate with us to enable this, please feel free to contact us.
Regards,
Cristian

**Comment by alexcarnero97** [comment]
Kafka-ML will have support for incremental training in the near future.

**Comment by cmfer** [comment]
We are happy to announce that Kafka-ML supports now incremental learning!
