### ISSUE TITLE
Build_Kafka_ML.sh in Windows Format

### ISSUE THREAD

**Issue by dgarridouma** [ertis-research/kafka-ml#81]
Hi,

I tried to use Build_Kafka_ML.sh in Ubuntu but it game some problems because the file seems to be in Windows format.

Solution: I used dos2unix utility to convert it to Linux format.

**Comment by adrisalas** [comment]
This was fixed 2 days ago in the commit: 9a08b33a99f571f0e36d0b81b2859eeabc7e5724
This could also be fixed in several text editors _(as VSCode)_ changing the end of line sequence from `CRLF` to `LF`

**Comment by dgarridouma** [comment]
Ok, I close the issue
