### ISSUE TITLE
Deployment is not not running with /proc/driver/nvidia/version does not exist

### ISSUE THREAD

**Issue by suojun-hao** [ertis-research/kafka-ml#99]
For example  we create a new MINST deployment however it could not be running as error 
"/proc/driver/nvidia/version does not exist"
2022-12-09 15:51:57.845894: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: UNKNOWN ERROR (34)
2022-12-09 15:51:57.845959: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (tfexecutor-7bc4bbdbf4-tw7sl): /proc/driver/nvidia/version does not exist

![image](https://user-images.githubusercontent.com/70371382/210395633-868e5e40-144a-4bad-ade4-a50a8d45e7e6.png)

We install vanilla K8s based on redhat8 then deploy kafka-ml on this k8s cluster, so we don't have GPU.

Please advise how we can disable GPU or fix the issue.

**Comment by antoniochavesgarcia** [comment]
Thank you for reporting this issue. It seems that your backend deployment is attempting to deploy GPU-accelerated images, even though your system does not have a GPU. This results in TensorFlow being unable to initialize the CUDA driver, leading to an error. **While this error will occur, the training should continue without further issues running in CPU**.

To resolve this problem and use more lightweight images, **you will need to disable the GPU in your backend deployment**. **To accomplish this, select images that do not have a GPU tag**. You can verify this by examining the YAML file that defines your backend deployment, ensuring that the specified images lack a GPU tag.

Please let me know if this solution resolves your problem or if you require additional assistance.
